

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tcm_backend
    ports:
      - "8001:8001"
    volumes:
      - ./json_data:/app/json_data
    env_file: .env
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: tcm_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  neo4j:
    image: neo4j:5.23
    container_name: tcm_neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/test12345
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
